In [1]:
import pandas as pd 
df1 = pd.read_csv("majestic_million.csv")


df1.size

12000000

In [2]:

df_15k = df1.sample(n=15000, random_state=42)

# Save to CSV
df_15k.to_csv("dataset_15k_random.csv", index=False)

In [5]:
df2 = pd.read_csv("dataset_15k_random.csv")
df2['url'] = "https://" + df2['Domain']
df2

,GlobalRank,TldRank,Domain,TLD,RefSubNets,RefIPs,IDN_Domain,IDN_TLD,PrevGlobalRank,PrevTldRank,PrevRefSubNets,PrevRefIPs,url
0,987232,74668,hannahshope.org,org,239,273,hannahshope.org,org,977006,74024,238,271,https://hannahshope.org
1,79955,35822,boxingnews24.com,com,1181,1569,boxingnews24.com,com,80493,36094,1175,1571,https://boxingnews24.com
2,567131,4160,mojedziecikreatywnie.pl,pl,346,447,mojedziecikreatywnie.pl,pl,570119,4200,342,444,https://mojedziecikreatywnie.pl
3,500892,224605,teleco.com,com,377,835,teleco.com,com,504815,226781,372,823,https://teleco.com
4,55400,1599,hackedbolt.ru,ru,1476,1809,hackedbolt.ru,ru,56059,1623,1462,1799,https://hackedbolt.ru
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,551655,4227,cienciaempresarial.com.br,br,353,456,cienciaempresarial.com.br,br,532478,4095,359,458,https://cienciaempresarial.com.br
14996,404056,12646,kleingarten-bund.de,de,436,699,kleingarten-bund.de,de,409266,12799,429,690,https://kleingarten-bund.de
14997,472239,17861,mytimeactive.co.uk,uk,392,475,mytimeactive.co.uk,uk,474617,17524,388,473,https://mytimeactive.co.uk
14998,653169,295422,casinogoodwins.com,com,312,624,casinogoodwins.com,com,615763,278767,323,611,https://casinogoodwins.com
14999,822339,4819,casinoselector-777.top,top,266,304,casinoselector-777.top,top,808723,4753,266,303,https://casinoselector-777.top

In [11]:
df3= df2[["url"]]
df3["label"]=0
df3["source"]="majestic"
df3

/tmp/ipykernel_103710/3266535999.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3["label"]=0
/tmp/ipykernel_103710/3266535999.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3["source"]="majestic"

                                     url  label    source
0                https://hannahshope.org      0  majestic
1               https://boxingnews24.com      0  majestic
2        https://mojedziecikreatywnie.pl      0  majestic
3                     https://teleco.com      0  majestic
4                  https://hackedbolt.ru      0  majestic
...                                  ...    ...       ...
14995  https://cienciaempresarial.com.br      0  majestic
14996        https://kleingarten-bund.de      0  majestic
14997         https://mytimeactive.co.uk      0  majestic
14998         https://casinogoodwins.com      0  majestic
14999     https://casinoselector-777.top      0  majestic

[15000 rows x 3 columns]

In [12]:
df3

                                     url  label    source
0                https://hannahshope.org      0  majestic
1               https://boxingnews24.com      0  majestic
2        https://mojedziecikreatywnie.pl      0  majestic
3                     https://teleco.com      0  majestic
4                  https://hackedbolt.ru      0  majestic
...                                  ...    ...       ...
14995  https://cienciaempresarial.com.br      0  majestic
14996        https://kleingarten-bund.de      0  majestic
14997         https://mytimeactive.co.uk      0  majestic
14998         https://casinogoodwins.com      0  majestic
14999     https://casinoselector-777.top      0  majestic

[15000 rows x 3 columns]

In [13]:
df3.to_csv("safe15kurls.csv", index=False)